##################################
# Performance viewer config file #
##################################

# Map image path
img_path: ${MUTAC_WS}/performance_evaluation/performance_viewer/src/performance_viewer/resources/solarfarm.png

# Top left corner and bottom right corner coordinates from the map
img_coordinates:
  top: [-13.61, 22.61]
  bottom: [230.75, -104.03]

# Points that form the region to inspect
regions:
  area1:
    - [-5, 8]
    - [58.85, 10]
    - [80.17, -91.83]
    - [22.86, -92.60]
    - [-5, 8]
  area2:
    - [75, 5.5]
    - [185, 9]
    - [215, -35]
    - [97.5, -60]
    - [89.58, -60]
    - [75, 5.5]
